version: '3'

services:
  app_dev:
    container_name: app_dev
    ports:
      - 5000:5000
    build:
      context: ../../
      dockerfile: compose/dev/Dockerfile
    networks:
      - xeneta_dev
    environment:
      DB_HOST: 'db_dev'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'postgres'
      ENVIRONMENT: 'testing'
    depends_on:
      - db_dev

networks:
  xeneta_dev:
